# Generated by Django 4.0.2 on 2022-02-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelingApp', '0002_customer_2_vehicle_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('worker', models.ManyToManyField(related_name='Machine', to='modelingApp.Worker')),
            ],
        ),
    ]
